services:
  postgres:
    image: postgres:17.2
    container_name: postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    # command: ['-c', 'config_file=/etc/postgresql/postgresql.conf']
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname mydatabase --username myuser "]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      # - ./logs:/logs
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
